/* 
 * Copyright 2011-2012 IS2T. All rights reserved.
 * Modification and distribution is permitted under certain conditions.
 * IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by COMP-ICETEA-ARMCC-ARM - 1.0.0 - DO NOT EDIT IT
 */
/* 
 * IceTea to C mapping support. Shall not be directly included by clients.
 */
#ifndef _LLMJVM_intern
#define _LLMJVM_intern 
typedef struct LLMJVM LLMJVM;
#include <stdint.h>
#ifdef __cplusplus
	extern "C" {
#endif
struct LLMJVM
{
	int32_t __icetea__id__;
};
#ifdef __cplusplus
	}
#endif
#endif
